[package]
name = "comms"
version = "0.1.4"
authors = ["Michael Mokrysz <hi@46b.it>"]

[dependencies]
futures = "0.1"
tokio-timer = "0.1"
clippy = {version = "*", optional = true}

[dev-dependencies]
quickcheck = "0.2"

[features]
default = []
dev = ["clippy"]
